### ISSUE TITLE
Use the real PrivateBin software

### ISSUE THREAD

**Issue by Kcchouette** [YunoHost-Apps/zerobin_ynh#14]
Hello

Is there a way to update the script to use the real PrivateBin ( https://github.com/PrivateBin/PrivateBin ) v1.1?

Thank you!

**Comment by M5oul** [comment]
It's already using a version 0.22 of PrivateBin. But, yes, it must be updated to lasted version +1.1.
Should we rename this app?
Does official app upgrade will still works if the name change?

**Comment by lapineige** [comment]
> Should we rename this app?

If it's not blocking for the update, I think it would be clearer.
You could also edit the readme and mention that it was the former ZeroBin app.

**Comment by M5oul** [comment]
### Todo:
- [ ] Update to version +1.1.
- [ ] rename package to _PasteBin_.

It would be better if the app could still be updated when changing the app id.
May we handle this case on YunoHost side?

**Comment by magikcypress** [comment]
My pull request work with a new version 1.1

**Comment by rugk** [comment]
Any news?

**Comment by JimboJoe** [comment]
Implemented by https://github.com/YunoHost-Apps/zerobin_ynh/commit/c0cebb4dec7029e51e6a2069f72253af62d72069
