### ISSUE TITLE
Do not use www-data

### ISSUE THREAD

**Issue by julienmalik** [YunoHost-Apps/zerobin_ynh#17]
The app shall create a specific system user and not rely on www-data, specifically because it needs write permission on the filesystem.
This implies declaring a specific php-fpm instance with this user, as is done with a lot of yunohost php apps now.

**Comment by JimboJoe** [comment]
@julienmalik Is that recommendation to apply to any YunoHost application, or are there specific criteria (you're stating "specifically because it needs write permission on the filesystem")?

**Comment by magikcypress** [comment]
After a discussion, we can not currently create a user for each application. Because some helpers are not present in production.

**Comment by magikcypress** [comment]
Add user for this app with a good helper PR #16

**Comment by frju365** [comment]
apparently solved with the https://github.com/YunoHost-Apps/zerobin_ynh/pull/16. So, I close this issue.
